### **Task 1 **

In [9]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print(df)

            Country         Region  Year   CO2_Mt  CO2_per_capita
0     United States  North America  2000   5857.6            1.32
1     United States  North America  2001   5724.0            1.26
2     United States  North America  2002   5652.8            1.11
3     United States  North America  2003   5592.8            1.29
4     United States  North America  2004   5743.2            1.12
5     United States  North America  2005   5589.0            1.32
6     United States  North America  2006   5385.5            1.09
7     United States  North America  2007   5442.9            1.10
8     United States  North America  2008   5348.1            1.14
9     United States  North America  2009   5038.1            1.04
10    United States  North America  2010   5082.5            1.05
11    United States  North America  2011   5176.5            1.09
12    United States  North America  2012   5250.0            1.06
13    United States  North America  2013   4993.8            1.08
14    United States  North America  2014   4896.9            1.08
15    United States  North America  2015   4912.9            0.99
16    United States  North America  2016   4770.3            1.07
17    United States  North America  2017   4746.2            1.01
18    United States  North America  2018   4718.4            0.92
19    United States  North America  2019   4537.3            1.06
20    United States  North America  2020   4695.4            0.97
21    United States  North America  2021   4398.4            0.95
22    United States  North America  2022   4325.9            1.02
23            China           Asia  2000   3513.8            1.32
24            China           Asia  2001   3951.7            1.30
25            China           Asia  2002   4312.0            1.45
26            China           Asia  2003   4691.9            1.64
27            China           Asia  2004   5078.9            1.73
28            China           Asia  2005   5467.8            1.87
29            China           Asia  2006   5974.0            2.15
30            China           Asia  2007   6322.7            2.07
31            China           Asia  2008   6673.0            2.62
32            China           Asia  2009   7052.6            2.27
33            China           Asia  2010   7542.8            2.86
34            China           Asia  2011   7972.2            3.00
35            China           Asia  2012   8365.2            2.73
36            China           Asia  2013   8641.3            3.31
37            China           Asia  2014   9078.4            3.32
38            China           Asia  2015   9466.5            3.25
39            China           Asia  2016   9887.0            3.41
40            China           Asia  2017  10356.9            3.99
41            China           Asia  2018  10794.9            3.83
42            China           Asia  2019  11125.3            4.18
43            China           Asia  2020  11454.8            4.14
44            China           Asia  2021  11897.5            4.27
45            China           Asia  2022  12409.5            4.37
46            India           Asia  2000    901.6            1.21
47            India           Asia  2001    974.6            1.36
48            India           Asia  2002   1056.0            1.44
49            India           Asia  2003   1146.4            1.67
50            India           Asia  2004   1205.4            1.82
51            India           Asia  2005   1291.0            1.90
52            India           Asia  2006   1396.5            2.06
53            India           Asia  2007   1465.9            1.91
54            India           Asia  2008   1541.7            2.27
55            India           Asia  2009   1637.4            2.45
56            India           Asia  2010   1687.4            2.22
57            India           Asia  2011   1774.1            2.43
58            India           Asia  2012   1865.3            2.34
59            India           Asia  2013   1944.7            2.71
60            India           Asia  2014   1994.5            2.56
61            India           Asia  2015   2092.4            2.81
62            India           Asia  2016   2177.1            3.04
63            India           Asia  2017   2267.3            3.28
64            India           Asia  2018   2344.6            3.56
65            India           Asia  2019   2418.7            3.19
66            India           Asia  2020   2465.5            3.28
67            India           Asia  2021   2579.5            3.25
68            India           Asia  2022   2661.1            3.36
69          Germany         Europe  2000    902.4            1.25
70          Germany         Europe  2001    831.7            1.12
71          Germany         Europe  2002    815.2            1.18
72          Germany         Europe  2003    804.7            1.11
73          Germany         Europe  2004    772.9            1.17
74          Germany         Europe  2005    759.1            1.13
75          Germany         Europe  2006    685.9            1.00
76          Germany         Europe  2007    668.0            0.88
77          Germany         Europe  2008    650.3            0.96
78          Germany         Europe  2009    608.3            0.91
79          Germany         Europe  2010    611.2            0.83
80          Germany         Europe  2011    569.2            0.90
81          Germany         Europe  2012    586.7            0.79
82          Germany         Europe  2013    521.5            0.82
83          Germany         Europe  2014    504.5            0.79
84          Germany         Europe  2015    499.0            0.77
85          Germany         Europe  2016    438.8            0.64
86          Germany         Europe  2017    407.4            0.54
87          Germany         Europe  2018    413.2            0.65
88          Germany         Europe  2019    389.5            0.55
89          Germany         Europe  2020    373.4            0.53
90          Germany         Europe  2021    344.0            0.54
91          Germany         Europe  2022    315.1            0.48
92   United Kingdom         Europe  2000    552.4            1.15
93   United Kingdom         Europe  2001    542.6            1.31
94   United Kingdom         Europe  2002    523.3            1.05
95   United Kingdom         Europe  2003    492.0            1.02
96   United Kingdom         Europe  2004    500.9            1.15
97   United Kingdom         Europe  2005    465.3            0.98
98   United Kingdom         Europe  2006    429.1            0.92
99   United Kingdom         Europe  2007    428.8            1.00
100  United Kingdom         Europe  2008    410.8            0.95
101  United Kingdom         Europe  2009    384.6            0.87
102  United Kingdom         Europe  2010    357.3            0.76
103  United Kingdom         Europe  2011    331.6            0.70
104  United Kingdom         Europe  2012    319.1            0.77
105  United Kingdom         Europe  2013    303.8            0.70
106  United Kingdom         Europe  2014    280.1            0.63
107  United Kingdom         Europe  2015    276.3            0.62
108  United Kingdom         Europe  2016    247.0            0.53
109  United Kingdom         Europe  2017    210.4            0.42
110  United Kingdom         Europe  2018    188.0            0.46
111  United Kingdom         Europe  2019    185.4            0.45
112  United Kingdom         Europe  2020    157.5            0.32
113  United Kingdom         Europe  2021    148.0            0.36
114  United Kingdom         Europe  2022    125.3            0.31
115          France         Europe  2000    389.4            1.34
116          France         Europe  2001    375.4            1.29
117          France         Europe  2002    362.2            1.12
118          France         Europe  2003    367.7            1.28
119          France         Europe  2004    348.3            1.16
120          France         Europe  2005    343.1            1.12
121          France         Europe  2006    343.2            1.21
122          France         Europe  2007    334.5            1.15
123          France         Europe  2008    317.1            1.07
124          France         Europe  2009    326.4            1.02
125          France         Europe  2010    318.2            0.98
126          France         Europe  2011    306.0            1.05
127          France         Europe  2012    298.0            1.03
128          France         Europe  2013    290.0            0.98
129          France         Europe  2014    308.1            1.02
130          France         Europe  2015    277.4            0.96
131          France         Europe  2016    267.1            0.83
132          France         Europe  2017    248.0            0.81
133          France         Europe  2018    244.2            0.71
134          France         Europe  2019    256.1            0.79
135          France         Europe  2020    215.4            0.70
136          France         Europe  2021    218.3            0.65
137          France         Europe  2022    222.5            0.72
138          Brazil  Latin America  2000    423.8            1.26
139          Brazil  Latin America  2001    445.8            1.19
140          Brazil  Latin America  2002    450.4            1.32
141          Brazil  Latin America  2003    454.4            1.36
142          Brazil  Latin America  2004    452.6            1.39
143          Brazil  Latin America  2005    481.6            1.34
144          Brazil  Latin America  2006    483.2            1.27
145          Brazil  Latin America  2007    499.0            1.58
146          Brazil  Latin America  2008    514.3            1.47
147          Brazil  Latin America  2009    527.4            1.43
148          Brazil  Latin America  2010    525.9            1.54
149          Brazil  Latin America  2011    534.4            1.62
150          Brazil  Latin America  2012    539.2            1.71
151          Brazil  Latin America  2013    567.9            1.73
152          Brazil  Latin America  2014    588.3            1.68
153          Brazil  Latin America  2015    588.9            1.63
154          Brazil  Latin America  2016    600.9            1.58
155          Brazil  Latin America  2017    593.9            1.59
156          Brazil  Latin America  2018    613.8            1.78
157          Brazil  Latin America  2019    626.7            1.68
158          Brazil  Latin America  2020    602.1            1.64
159          Brazil  Latin America  2021    631.2            1.81
160          Brazil  Latin America  2022    664.0            1.98
161           Japan           Asia  2000   1165.7            1.10
162           Japan           Asia  2001   1219.6            1.27
163           Japan           Asia  2002   1135.5            1.27
164           Japan           Asia  2003   1131.4            1.08
165           Japan           Asia  2004   1151.1            1.23
166           Japan           Asia  2005   1126.7            1.28
167           Japan           Asia  2006   1100.8            1.16
168           Japan           Asia  2007   1133.1            1.17
169           Japan           Asia  2008   1050.3            1.10
170           Japan           Asia  2009   1061.4            1.21
171           Japan           Asia  2010   1064.1            1.20
172           Japan           Asia  2011   1041.7            0.99
173           Japan           Asia  2012   1005.1            1.01
174           Japan           Asia  2013    990.9            0.95
175           Japan           Asia  2014   1010.4            1.09
176           Japan           Asia  2015    996.6            1.09
177           Japan           Asia  2016    967.4            1.07
178           Japan           Asia  2017    925.1            1.01
179           Japan           Asia  2018    916.6            1.01
180           Japan           Asia  2019    914.5            0.93
181           Japan           Asia  2020    902.8            0.99
182           Japan           Asia  2021    898.1            1.00
183           Japan           Asia  2022    865.1            0.89
184          Canada  North America  2000    589.6            1.17
185          Canada  North America  2001    584.4            1.36
186          Canada  North America  2002    585.1            1.22
187          Canada  North America  2003    565.2            1.31
188          Canada  North America  2004    563.8            1.32
189          Canada  North America  2005    553.5            1.21
190          Canada  North America  2006    540.5            1.12
191          Canada  North America  2007    569.3            1.18
192          Canada  North America  2008    553.4            1.26
193          Canada  North America  2009    544.2            1.24
194          Canada  North America  2010    529.9            1.04
195          Canada  North America  2011    514.6            1.12
196          Canada  North America  2012    531.3            1.11
197          Canada  North America  2013    513.3            1.02
198          Canada  North America  2014    514.8            1.14
199          Canada  North America  2015    498.5            0.99
200          Canada  North America  2016    502.8            0.99
201          Canada  North America  2017    489.1            1.12
202          Canada  North America  2018    484.5            0.96
203          Canada  North America  2019    487.7            1.15
204          Canada  North America  2020    463.2            1.06
205          Canada  North America  2021    458.7            1.08
206          Canada  North America  2022    461.7            1.05
207       Australia        Oceania  2000    378.4            1.26
208       Australia        Oceania  2001    391.5            1.19
209       Australia        Oceania  2002    388.8            1.28
210       Australia        Oceania  2003    394.9            1.18
211       Australia        Oceania  2004    397.8            1.21
212       Australia        Oceania  2005    407.5            1.41
213       Australia        Oceania  2006    403.7            1.35
214       Australia        Oceania  2007    414.2            1.30
215       Australia        Oceania  2008    423.1            1.49
216       Australia        Oceania  2009    426.7            1.28
217       Australia        Oceania  2010    430.1            1.43
218       Australia        Oceania  2011    435.2            1.47
219       Australia        Oceania  2012    443.8            1.52
220       Australia        Oceania  2013    461.4            1.54
221       Australia        Oceania  2014    444.2            1.58
222       Australia        Oceania  2015    471.6            1.48
223       Australia        Oceania  2016    453.9            1.40
224       Australia        Oceania  2017    448.9            1.50
225       Australia        Oceania  2018    466.0            1.40
226       Australia        Oceania  2019    477.6            1.51
227       Australia        Oceania  2020    494.3            1.73
228       Australia        Oceania  2021    478.2            1.70
229       Australia        Oceania  2022    493.7            1.73
230     South Korea           Asia  2000    438.1            1.32
231     South Korea           Asia  2001    481.5            1.44
232     South Korea           Asia  2002    490.6            1.50
233     South Korea           Asia  2003    490.8            1.27
234     South Korea           Asia  2004    494.6            1.50
235     South Korea           Asia  2005    537.2            1.59
236     South Korea           Asia  2006    539.0            1.47
237     South Korea           Asia  2007    566.1            1.50
238     South Korea           Asia  2008    570.0            1.67
239     South Korea           Asia  2009    585.4            1.77
240     South Korea           Asia  2010    595.9            1.64
241     South Korea           Asia  2011    620.6            1.60
242     South Korea           Asia  2012    631.1            1.66
243     South Korea           Asia  2013    649.6            1.87
244     South Korea           Asia  2014    646.2            1.66
245     South Korea           Asia  2015    686.5            1.97
246     South Korea           Asia  2016    704.0            1.96
247     South Korea           Asia  2017    706.0            2.10
248     South Korea           Asia  2018    738.5            2.21
249     South Korea           Asia  2019    750.8            2.05
250     South Korea           Asia  2020    755.8            2.19
251     South Korea           Asia  2021    777.3            2.04
252     South Korea           Asia  2022    789.5            2.15
253          Russia         Europe  2000   1495.5            1.19
254          Russia         Europe  2001   1531.6            1.24
255          Russia         Europe  2002   1552.2            1.32
256          Russia         Europe  2003   1570.5            1.36
257          Russia         Europe  2004   1467.2            1.29
258          Russia         Europe  2005   1447.2            1.16
259          Russia         Europe  2006   1488.3            1.32
260          Russia         Europe  2007   1415.9            1.17
261          Russia         Europe  2008   1467.2            1.12
262          Russia         Europe  2009   1471.4            1.11
263          Russia         Europe  2010   1420.9            1.11
264          Russia         Europe  2011   1438.1            1.20
265          Russia         Europe  2012   1459.6            1.10
266          Russia         Europe  2013   1403.6            1.06
267          Russia         Europe  2014   1385.4            1.03
268          Russia         Europe  2015   1396.7            1.06
269          Russia         Europe  2016   1357.9            1.07
270          Russia         Europe  2017   1440.9            1.05
271          Russia         Europe  2018   1371.1            1.17
272          Russia         Europe  2019   1338.3            1.16
273          Russia         Europe  2020   1356.6            1.19
274          Russia         Europe  2021   1336.5            1.14
275          Russia         Europe  2022   1323.1            1.12
276    South Africa         Africa  2000    425.4            1.20
277    South Africa         Africa  2001    430.0            1.25
278    South Africa         Africa  2002    427.0            1.23
279    South Africa         Africa  2003    456.8            1.39
280    South Africa         Africa  2004    455.0            1.33
281    South Africa         Africa  2005    457.7            1.34
282    South Africa         Africa  2006    458.9            1.34
283    South Africa         Africa  2007    456.8            1.26
284    South Africa         Africa  2008    463.5            1.22
285    South Africa         Africa  2009    462.8            1.30
286    South Africa         Africa  2010    474.4            1.27
287    South Africa         Africa  2011    475.7            1.49
288    South Africa         Africa  2012    504.5            1.55
289    South Africa         Africa  2013    502.6            1.46
290    South Africa         Africa  2014    500.7            1.48
291    South Africa         Africa  2015    497.6            1.52
292    South Africa         Africa  2016    501.1            1.39
293    South Africa         Africa  2017    513.4            1.45
294    South Africa         Africa  2018    528.0            1.49
295    South Africa         Africa  2019    541.4            1.73
296    South Africa         Africa  2020    518.0            1.39
297    South Africa         Africa  2021    539.8            1.46
298    South Africa         Africa  2022    534.4            1.46
299          Mexico  Latin America  2000    415.9            1.18
300          Mexico  Latin America  2001    428.4            1.25
301          Mexico  Latin America  2002    429.0            1.40

In [10]:
df_asia = df[df['Region'] == 'Asia']
df_asia.head()

   Country Region  Year  CO2_Mt  CO2_per_capita
23   China   Asia  2000  3513.8            1.32
24   China   Asia  2001  3951.7            1.30
25   China   Asia  2002  4312.0            1.45
26   China   Asia  2003  4691.9            1.64
27   China   Asia  2004  5078.9            1.73

In [11]:
top_countries = (
    df_asia[df_asia['Year'] == 2022]
    .sort_values(by='CO2_Mt', ascending=False)
    .head(5)['Country']
)

df_top = df_asia[df_asia['Country'].isin(top_countries)]
print(top_countries)

45           China
68           India
344      Indonesia
183          Japan
252    South Korea
Name: Country, dtype: object

In [17]:
import plotly.graph_objects as go

fig = go.Figure()

for country in top_countries:
    temp = df_top[df_top['Country'] == country]

    fig.add_trace(go.Scatter(
        x=temp['Year'],
        y=temp['CO2_Mt'],
        mode='lines',
        line=dict(color='grey', width=5),
        showlegend=True
    ))

fig.show()

In [21]:
highlight = 'china'

temp = df_top[df_top['Country'] == highlight]

fig.add_trace(go.Scatter(
    x=temp['Year'],
    y=temp['CO2_Mt'],
    mode='lines',
    line=dict(color='red', width=3),
    name=highlight
))

fig.show()

In [22]:
fig.update_layout(
    title="China drives CO2 emission growth in Asia",
    plot_bgcolor='white',
    paper_bgcolor='white',
    font=dict(family="Arial"),
    xaxis=dict(showgrid=False),
    yaxis=dict(showgrid=False)
)

fig.show()

## **Task 2 **

In [29]:
df_slope = df[df['Year'].isin([2000, 2022])]
df_avg = df_slope.groupby(['Region', 'Year'])['CO2_Mt'].mean().reset_index()
pivot = df_avg.pivot(index='Region', columns='Year', values='CO2_Mt').dropna()
pivot

Year               2000     2022
Region
Africa          425.400   534.40
Asia           1280.400  3531.14
Europe          834.925   496.50
Latin America   419.850   629.15
North America  3223.600  2393.80
Oceania         378.400   493.70

In [34]:
import plotly.graph_objects as go

fig2 = go.Figure()

for region in pivot.index:
    fig2.add_trace(go.Scatter(
        x=[2000, 2022],
        y=[pivot.loc[region, 2000], pivot.loc[region, 2022]],
        mode='lines+markers',
        name=region,
        line=dict(width=2),
        marker=dict(size=6),
        hovertemplate=f"{region}<br>Year: %{{x}}<br>Value: %{{y}}<extra></extra>"
    ))

fig2.update_layout(
    title="Change from 2000 to 2022 by Region",
    xaxis_title="Year",
    yaxis_title="Value",
    template="plotly_white",
    legend_title="Region",
    hovermode="x unified"
)

fig2.show()